add rollback tag input

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,12 +2,34 @@ name: Release
 
 on:
   workflow_dispatch:
+    inputs:
+      rollback_tag:
+        description: 'Rollback tag (e.g., X.Y.Z)'
+        type: string
 
 permissions:
   contents: write
 
 jobs:
+  validate-rollback-tag:
+    runs-on: ubuntu-latest
+    outputs:
+      status: ${{ steps.validate_tag.outputs.status }}
+    steps:
+      - name: Validate tag
+        id: validate_tag
+        run: |
+          if [[ "${{ github.event.inputs.rollback_tag }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "TAG=${{ github.event.inputs.rollback_tag }}" >> $GITHUB_ENV
+          else
+            echo "Invalid rollback tag format. Expected format: X.Y.Z"
+            echo "rollback=false" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+
   calculate-version:
+    if: ${{ needs.validate-rollback-tag.outputs.status == 'failure' }}
+    needs: [validate-rollback-tag]
     runs-on: ubuntu-latest
     outputs:
       new_tag: ${{ steps.tag_version_dry_run.outputs.new_tag }}
@@ -23,9 +45,14 @@ jobs:
           custom_release_rules: config:patch:Configuration Changes,chore:patch:Miscellaneous,
           dry_run: true
 
+      - name: Update TAG Env
+        run: |
+          echo "TAG=${{ steps.tag_version_dry_run.outputs.new_tag }}" >> $GITHUB_ENV
+
   create-release:
+    if: ${{ needs.validate-rollback-tag.outputs.status == 'failure' }}
     runs-on: ubuntu-latest
-    needs: [calculate-version]
+    needs: [validate-rollback-tag, calculate-version]
     outputs:
       status: ${{ steps.failure.outputs.status }}
       changelog: ${{ steps.tag_version.outputs.changelog }}
@@ -51,7 +78,7 @@ jobs:
 
   bump-release-branch:
     runs-on: ubuntu-latest
-    needs: [calculate-version, create-release]
+    needs: [calculate-version, create-release, validate-rollback-tag]
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -59,7 +86,8 @@ jobs:
           ref: release
 
       - name: Reset release branch to latest release
+        if: ${{ needs.validate-rollback-tag.outputs.status == 'success' }}
         run: |
           git fetch origin --tags
-          git reset --hard ${{ needs.calculate-version.outputs.new_tag }}
+          git reset --hard $TAG
           git push origin release --force
