switch to use outputs instead of env

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,31 +10,8 @@ on:
 permissions:
   contents: write
 
-env:
-  TAG: ''
-
 jobs:
-  validate-rollback-tag:
-    runs-on: ubuntu-latest
-    continue-on-error: true
-    outputs:
-      status: ${{ steps.validate_tag.outputs.status }}
-      rollback: ${{ steps.validate_tag.outputs.rollback }}
-    steps:
-      - name: Validate tag
-        id: validate_tag
-        run: |
-          if [[ "${{ github.event.inputs.rollback_tag }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "TAG=${{ github.event.inputs.rollback_tag }}" >> $GITHUB_ENV
-            echo "rollback=true" >> $GITHUB_OUTPUT
-          else
-            echo "Invalid rollback tag format. Expected format: X.Y.Z"
-            echo "rollback=false" >> $GITHUB_OUTPUT
-          fi
-
   calculate-version:
-    if: ${{ needs.validate-rollback-tag.outputs.rollback == 'false' }}
-    needs: [validate-rollback-tag]
     runs-on: ubuntu-latest
     outputs:
       new_tag: ${{ steps.tag_version_dry_run.outputs.new_tag }}
@@ -51,8 +28,33 @@ jobs:
           dry_run: true
 
       - name: Update TAG Env
+        run: echo "TAG=${{ steps.tag_version_dry_run.outputs.new_tag }}" >> $GITHUB_ENV
+
+  validate-rollback-tag:
+    runs-on: ubuntu-latest
+    needs: calculate-version
+    continue-on-error: true
+    outputs:
+      status: ${{ steps.validate_tag.outputs.status }}
+      rollback: ${{ steps.validate_tag.outputs.rollback }}
+      tag: ${{ steps.validate_tag.outputs.tag }}
+    steps:
+      - name: Validate tag
+        if: "${{ github.event.inputs.rollback_tag != '' }}"
+        id: validate_tag
         run: |
-          echo "TAG=${{ steps.tag_version_dry_run.outputs.new_tag }}" >> $GITHUB_ENV
+          if [[ "${{ github.event.inputs.rollback_tag }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "TAG=${{ github.event.inputs.rollback_tag }}" >> $GITHUB_OUTPUT
+            echo "rollback=true" >> $GITHUB_OUTPUT
+          else
+            if [[ "${{ github.event.inputs.rollback_tag }}" == '' ]]; then
+              echo "TAG=${{ needs.calculate-version.outputs.new_tag }}" >> $GITHUB_OUTPUT
+              echo "rollback=false" >> $GITHUB_OUTPUT
+            else
+              echo "Invalid rollback tag format. Expected format: X.Y.Z"
+              exit 1
+            fi
+          fi
 
   create-release:
     if: ${{ needs.validate-rollback-tag.outputs.rollback == 'false' }}
@@ -92,7 +94,7 @@ jobs:
 
       - name: Reset release branch to selected release
         run: |
-          echo "Resetting release branch to ${{ env.TAG }}..."
+          echo "Resetting release branch to ${{ needs.validate-rollback-tag.outputs.tag }}..."
           git fetch origin --tags
-          git reset --hard ${{ env.TAG }}
+          git reset --hard ${{ needs.validate-rollback-tag.outputs.tag }}
           git push origin release --force
